name: glade
version: git
summary: Create or open user interface designs for GTK+ applications
description: |

  Glade is a RAD tool to enable quick & easy development of user interfaces
  for the GTK+ 3 toolkit and the GNOME desktop environment.

  The user interfaces designed in Glade are saved as XML and these can be
  loaded by applications dynamically as needed by using GtkBuilder or used
  directly to define a new GtkWidget derived object class using
  GTK+ new template feature.

  By using GtkBuilder, Glade XML files can be used in numerous programming
  languages including C, C++, C#, Vala, Java, Perl, Python, and others.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core18

plugs:
  gnome-3-28-1804:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-28-1804
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

apps:
  glade:
    command: desktop-launch glade
    plugs:
      - desktop
      - desktop-legacy
      - home
      - gsettings
      - network
      - unity7
      - wayland
    desktop: usr/share/applications/glade.desktop

parts:
  desktop-gnome-platform:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - build-essential
      - libgtk-3-dev
    override-build: |
      snapcraftctl build
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform

  glade:
    after: [desktop-gnome-platform]
    source: .
    source-type: git
    plugin: autotools
    configflags: [--disable-maintainer-mode, --prefix=/snap/glade/current/usr]
    override-build: |
      sed -i.bak -e 's|=glade$|=${SNAP}/meta/gui/glade.png|g' data/glade.desktop.in.in
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../src/data/icons/hicolor/256x256/apps/glade.png $SNAPCRAFT_PART_INSTALL/meta/gui/
    organize:
      snap/glade/current/usr: usr
    build-packages:
      - gnome-common
      - libxml2-dev
      - libglib2.0-dev
      - libgtk-3-dev
      - python-gi-dev
      - python2.7-dev
      - gtk-doc-tools
      - yelp-tools
      - intltool
      - gobject-introspection
      - libgirepository1.0-dev
